name = "InstantiateFromURL"
uuid = "f04cf714-cbf6-11e8-0aee-efd32d09e63e"
authors = ["Arnav Sood <soodarnav01@gmail.com>", "Jesse Perla <jesseperla@gmail.com>"]
version = "0.1.0"

[deps]
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
